### ISSUE TITLE
Можно именить список магазинов из вне, нарушив целостность данных

### ISSUE THREAD

**Issue by garlik6** [GPUStore/gpus_agrgtr#12]
```java
    @Test
    void nullifyingStores() throws IOException {
        //mockito stuff
        Product product = technoparkParser.getAllProducts().get(0);
        product.setStores(null);// <--------- here
        assertNotNull(product.getStores());
    }
```

**Comment by alekseiiagnenkov** [comment]
Что значит извне? Пользователь не сможем изменить снаружи это

**Comment by garlik6** [comment]
Ну я, как пользователь твоего класса, могу обнулить все магазины, которые были. Надо сделать не setStores а addStores, чтобы не было доступа к private переменной такого, это как иметь возможность обнулить корень дерева.

**Comment by SlaykSD** [comment]
Тоже самое можно сказать про страну, вес и тд. Это просто сущность. Может тогда все сетереры уберем и оставим чисто конструктор? В чем смысл тогда использовать эту сущность?

**Comment by alekseiiagnenkov** [comment]
В данном случае мы разрабочики, мы вообще можем все сделать тут. Но ты явно знаешь, что можно делать, а что нет. Вот если бы пользователь(тот, кто будет юзать наш магазин, мог бы стереть, то да, было бы не круто, надо было бы исправлять) А так в этом и есть прикол простого класса, который просто говорит тебе, вот я такой, делай со мной что хочешь. его методы очевидны, они не содержат внутри себя бизнес логику, а значит не заставляют задумываться о глубине и о том, есть ли там проверка на null(конечно нет), потому что это обычный setter.Даже Андросов говорил, что get и set должны только отдавать и заменять, ничего более
